addons:
  artifacts:
    debug: true
    paths:
    - libs.zip
    - build.zip
    - testbuild.zip
    - jacoco.exec
    target_paths: c1d2a91d-7279-415a-add9-807e13bceadc
  postgresql: '9.3'
after_success:
- ' wget --content-disposition http://search.maven.org/remotecontent?filepath=org/jacoco/jacoco/0.7.7.201606060606/jacoco-0.7.7.201606060606.zip '
- ' unzip -o jacoco-0.7.7.201606060606.zip  '
- ' cd lib  '
- ' mv * ../  '
- ' cd ..  '
- ' chmod a+x *  '
- ' cd $PWD  '
- ' rm  ''jacoco.exec'''
- ' export JAVA_TOOL_OPTIONS=-javaagent:$PWD/jacocoagent.jar=destfile=$PWD/jacoco.exec,append=true  '
- ' travis_wait 720 mvn  test -Dmaven.test.failure.ignore=true -Djacoco.skip=true
  -Dcobertura.skip=true -Dmaven.clover.skip=true -Dmaven.javadoc.skip=true -Drat.skip=true
  -Drat.ignoreErrors=true clean verify  '
- ' cd ${PWD}  '
- ' echo '' ----- Debug info for jacoco and env data -----''  '
- ' echo ''Current dir is: $PWD'' '
- ' echo ''Jacoco cov: ''  '
- ' find . -name ''*.exec''  '
- ' echo '' ----------------------------------------------'' '
- ./df-build.sh
before_install: []
before_script:
- mysql -u root -e "source travis/mysql.sql"
- psql -U postgres -f travis/postgresql.sql
- psql -c 'create extension postgis;' -d querydsl -U postgres
- ./travis/cubrid.sh
- ./travis/firebird.sh
branches: ''
cache:
  directories:
  - $HOME/.m2
  - $HOME/.m2
env:
  matrix:
  - MODULE=!querydsl-scala PROFILES=all,travis,examples
  - MODULE=!querydsl-jpa-codegen PROFILES=jpa,hibernate5,travis,examples
  - MODULE=querydsl-scala PROFILES=all,travis
install:
- mvn -B -q --projects ${MODULE} -P${PROFILES} install -DskipTests=true
jdk:
- oraclejdk8
language: java
notifications:
  webhooks:
    on_failure: always
    on_start: always
    on_success: always
    urls:
    - http://insights-portal-insights-service-webserver-dev.public-swarm.devfactory.com/travisWebHookListener?build_id=c1d2a91d-7279-415a-add9-807e13bceadc
script:
- mvn -B test -P${PROFILES} --projects ${MODULE} jacoco:report
services:
- mongodb
sudo: required
# Modified by Insights Service at 2016-11-27 19:20:13.705382
